name: Automating README

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Node
        uses: actions/setup-node@v1
      - name: Install modules
        run: npm install
      - name: Generate README
        run: node index.js
      - name: Push to Github
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
